barbeau/gpstest

- .travis.yml
- GPSTest/build.gradle
- GPSTest/src/main/AndroidManifest.xml
- GPSTest/src/main/java/com/android/gpstest/GpsStatusFragment.java
- GPSTest/src/main/java/com/android/gpstest/GpsTestActivity.java
- GPSTest/src/main/java/com/android/gpstest/util/GpsTestUtil.java
- GPSTest/src/main/java/com/android/gpstest/util/MathUtils.java
- GPSTest/src/main/res/layout/gps_status.xml
- GPSTest/src/main/res/layout/gps_switch.xml
- GPSTest/src/main/res/layout/status_row_item.xml
- GPSTest/src/main/res/menu/gps_menu.xml
- GPSTest/src/main/res/values/dimens.xml
- GPSTest/src/main/res/values/strings.xml
- GPSTest/src/main/res/values/styles.xml
- GPSTest/src/main/res/values/themes.xml
- GPSTest/src/test/java/com/android/gpstest/GpsTestUtilTest.java
- GPSTest/src/test/java/com/android/gpstest/MathUtilTest.java
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
~~**WIP - Please don't merge**~~
TODO:
> WIP - Fix #103 - Add carrier frequency

- GPSTest/src/main/java/com/android/gpstest/util/GpsTestUtil.java
This change displays the flags for WAAS IDs 48 and 51 for Android versions below 7.0.
While I was at it, I moved NAVSTAR to the top, both for numerical order and to have it first in the decision tree instead of last (as it tends to be pretty popular for older chipsets).
Here's a screenshot.
> Fix #100 - Flags for WAAS IDs 48 & 51

- GPSTest/src/main/res/layout/status_row_item.xml
With the change from GridView to RecyclerView (#104), a change was made from GridView's rowHeight of 16dp and verticalSpacing of 1dp to... well, they simply weren't retained. Due to the sizes of the flag images (they're squares instead of rectangles), the rows grew higher to accommodate them, causing fewer rows to appear on the screen -- on my 4.5" 720x1280 Moto G, the number of rows went from 16 to 13. This proposed change (-2.5dp vertical margin) restores the layout to the previous row height. (I did try setting layout_height to 16dp, but that caused the `ScaleType.FIT_START` to resize the flag smaller.)
Note: I haven't tested this on any other devices, so I don't know if the same row count change will occur elsewhere. (I'm on WinXP, no Intel HAXM support for emulator images, 'twas a …
> Change flag margins to restore previous row height

- GPSTest/src/main/java/com/android/gpstest/Application.java
- GPSTest/src/main/java/com/android/gpstest/BenchmarkController.java
- GPSTest/src/main/java/com/android/gpstest/BenchmarkControllerImpl.java
- GPSTest/src/main/java/com/android/gpstest/GpsStatusFragment.java
- GPSTest/src/main/java/com/android/gpstest/GpsTestActivity.java
- GPSTest/src/main/java/com/android/gpstest/Preferences.java
- GPSTest/src/main/java/com/android/gpstest/lang/LocaleManager.java
- GPSTest/src/main/java/com/android/gpstest/util/LocaleUtils.java
- GPSTest/src/main/java/com/android/gpstest/util/UIUtils.java
- GPSTest/src/main/res/values-cs-rCZ/arrays.xml
- GPSTest/src/main/res/values-de-rDE/arrays.xml
- GPSTest/src/main/res/values-el/arrays.xml
- GPSTest/src/main/res/values-it/arrays.xml
- GPSTest/src/main/res/values-it/strings.xml
- GPSTest/src/main/res/values-ja/arrays.xml
- GPSTest/src/main/res/values-nl/arrays.xml
- GPSTest/src/main/res/values-zh-rCN/arrays.xml
- GPSTest/src/main/res/values/arrays.xml
- GPSTest/src/main/res/values/do_not_translate.xml
- GPSTest/src/main/res/values/strings.xml
- GPSTest/src/main/res/xml/preferences.xml
- TRANSLATIONS.md
> Fix #284 - Allow user to change language within app

- GPSTest/src/androidTest/java/com/android/gpstest/UIUtilsAndroidTest.java
- GPSTest/src/main/java/com/android/gpstest/GpsStatusFragment.java
- GPSTest/src/main/java/com/android/gpstest/util/UIUtils.java
- GPSTest/src/main/res/values-ja/strings.xml
- GPSTest/src/main/res/values-nl/strings.xml
- GPSTest/src/main/res/values/arrays.xml
- GPSTest/src/main/res/values/do_not_translate.xml
- GPSTest/src/main/res/values/strings.xml
- GPSTest/src/main/res/xml/preferences.xml
This is a version of https://github.com/barbeau/gpstest/pull/243 merged with the master branch, which I'll use to finish off this feature.
TODO:
> Fix #242 - Support Degrees Decimal Minutes coordinate format

- GPSTest/src/main/java/com/android/gpstest/util/UIUtils.java
Allow users to select an email app to send feedback through, while removing apps which do not explicitly handle the `mailto` URI.
Technically this will still allow the selection of non-email clients (👀 PayPal), but it will reduce the app selection to more reasonable options. There is no way of excluding apps which hijack URIs, so this is the next best thing.
---
Setting the MIME type to `message/rfc822` does not seem to be compatible with the `mailto` URL, resulting in an empty intent picker.
Using the `ACTION_SEND` intent does not seem to be compatible with the `mailto` URI, but this is undocumented _AFAIK_.
---
> Fix #324 - Limit feedback to email apps

- .travis.yml
- tools/android-wait-for-emulator.sh
Based on https://github.com/googlemaps/android-maps-utils/pull/590.
This allows us to use higher level API emulator versions (we're currently stuck on 18).
> Manually install JDK and Android SDK on Travis

- GPSTest/src/androidTest/java/com/android/gpstest/DeviceInfoViewModelTest.kt
- GPSTest/src/androidTest/java/com/android/gpstest/TestUtils.kt
- GPSTest/src/main/java/com/android/gpstest/DeviceInfoViewModel.java
- GPSTest/src/main/java/com/android/gpstest/GpsStatusFragment.java
- GPSTest/src/main/java/com/android/gpstest/model/ConstellationFamily.kt
- GPSTest/src/main/java/com/android/gpstest/model/SatelliteMetadata.kt
- GPSTest/src/main/res/values/do_not_translate.xml
- GPSTest/src/main/res/values/strings.xml
> Fix #365 - Use C/N0 values when counting signals/sats in view

- FAQ.md
- GPSTest/src/main/java/com/android/gpstest/GpsStatusFragment.java
- GPSTest/src/main/java/com/android/gpstest/util/DateTimeUtils.kt
- GPSTest/src/main/res/drawable/error_text_background.xml
- GPSTest/src/main/res/layout/error_text_dialog.xml
- GPSTest/src/main/res/layout/gps_status.xml
- GPSTest/src/main/res/values/strings.xml
- GPSTest/src/main/res/values/styles.xml
- GPSTest/src/test/java/com/android/gpstest/util/DateTimeUtilsTest.kt
- GPSTest/src/test/java/com/android/gpstest/util/MathUtilTest.java
- GPSTest/src/test/java/com/android/gpstest/util/NmeaUtilsTest.java
- GPSTest/src/test/java/com/android/gpstest/util/UIUtilsTest.java
This shows GNSS times that are more than 5 days different than the system clock with a red background, and if you tap on it it shows an error dialog with a link to more info on GPS week rollover.
TODO:
> Fix #369 - Highlight wrong GNSS times on Status

- GPSTest/src/main/java/com/android/gpstest/GpsStatusFragment.java
- GPSTest/src/main/java/com/android/gpstest/util/UIUtils.java
This adds date to the Status view when the screen width is more than 450dp (including when the screen is rotated to landscape).
Closes #409.
Here are example screenshots from a Samsung Galaxy S8+ - the date doesn't appear when in portrait but appears in landscape:
TODO:
> feat: Add date to Status view for wide screens

- .travis.yml
- GPSTest/build.gradle
- GPSTest/src/androidTest/java/com/android/gpstest/IOUtilsTest.kt
- GPSTest/src/main/java/com/android/gpstest/util/SatelliteUtils.java
Also changes to canonical GnssStatus.CONSTELLATION_IRNSS, and therefore closes #340.
Closes #340
Closes #420
> chore: Bump compile/targetSdkVerion, build tools

- GPSTest/src/main/java/com/android/gpstest/GpsTestActivity.java
- GPSTest/src/main/java/com/android/gpstest/util/UIUtils.java
- GPSTest/src/main/res/drawable/ic_baseline_lock_24.xml
- GPSTest/src/main/res/layout/content_main.xml
This PR adds a progress bar that is shown when the GNSS is attempting to acquire a fix (including after it's acquired but then lost a fix), and disappears when a lock is acquired. A lock icon that has the inverse behavior will also be shown.
TODO:
Closes #417
> feat: Add indicators for acquiring/acquired GNSS fix

- GPSTest/src/main/java/com/android/gpstest/dialog/ShareDialogFragment.kt
- GPSTest/src/main/java/com/android/gpstest/dialog/ShareLocationFragment.kt
- GPSTest/src/main/java/com/android/gpstest/dialog/ShareLogFragment.kt
- GPSTest/src/main/java/com/android/gpstest/dialog/UploadDeviceInfoFragment.kt
Remove unused parameters in Kotlin code.. This reduces the unused warnings from the
Kotlin compiler during build. Also,  prevents IllegalArgumentException if parameter was null and
was marked non-null.
- see https://kotlinlang.org/docs/reference/lambdas.html#underscore-for-unused-variables-since-11
> chore: Remove unused parameters in Kotlin code

- GPSTest/src/google/java/com/android/gpstest/GpsMapFragment.java
- GPSTest/src/main/java/com/android/gpstest/GpsSkyFragment.java
- GPSTest/src/main/java/com/android/gpstest/GpsTestActivity.java
- GPSTest/src/main/java/com/android/gpstest/view/GpsSkyView.java
Android Studio analyzer caught these. These changes will reduce the warnings in Android Studio.
fyi - As a side note, I do find when working in Java code it is preferable to use "Java style"
array definitions as opposed to "C style".. It helps me to think in the right paradigm..
> chore: cleanup various code style warnings..

- GPSTest/src/google/java/com/android/gpstest/GpsMapFragment.java
- GPSTest/src/main/java/com/android/gpstest/GpsTestActivity.java
- GPSTest/src/main/java/com/android/gpstest/NavigationDrawerFragment.java
- GPSTest/src/main/java/com/android/gpstest/util/IOUtils.java
- GPSTest/src/main/java/com/android/gpstest/util/NmeaUtils.java
- GPSTest/src/main/java/com/android/gpstest/util/UIUtils.java
This "bug report" is really about doing some very basic code cleanup. No functionality has been changed.
1 - cleaned up the autoboxing.. valueOf() returns an Object type where parseXXX() returns a primitive type.
Several places primitive types are used instead of Objects.
2 - A couple of places just simply use the diamond operator.
3 - A couple of places lambda is treated as a statement.. Really minor semantics
Expected behavior
A few less warnings will be emitted by the Android Studio..
Observed behavior
A few warnings from the Android Studio IDE.
Closes https://github.com/barbeau/gpstest/issues/517
> chore: Cleanup the code a little bit

- wear/src/main/java/com/android/gpstest/wear/MainActivity.kt
When the Wear OS app is first started, the user interface populates with default (i.e., not real) GNSS information. They should be initialized to empty values.
Close #609
> fix: Initialize UI with empty values on Wear OS

- GPSTest/build.gradle
- GPSTest/src/androidTest/java/com/android/gpstest/FormatUtilsTest.kt
- GPSTest/src/main/AndroidManifest.xml
- GPSTest/src/main/java/com/android/gpstest/ForegroundOnlyLocationService.kt
- GPSTest/src/main/java/com/android/gpstest/io/BaseFileLogger.java
- GPSTest/src/main/java/com/android/gpstest/io/CsvFileLogger.java
- GPSTest/src/main/java/com/android/gpstest/ui/MainActivity.kt
- GPSTest/src/main/java/com/android/gpstest/ui/Preferences.kt
- GPSTest/src/main/java/com/android/gpstest/ui/status/StatusScreen.kt
- LOGGING.md
- build.gradle
- library/src/main/java/com/android/gpstest/library/util/FormatUtils.kt
- library/src/main/java/com/android/gpstest/library/util/PermissionUtils.java
- library/src/main/res/values/strings.xml
- wear/build.gradle
This PR updates the app to support `targetSdkVersion 31`, including:
Fixes #619, #447 
> chore: Target SDK version 31

- GPSTest/src/androidTest/java/com/android/gpstest/CarrierFreqUtilsTest.kt
- fastlane/metadata/android/en-US/full_description.txt
- library/src/main/java/com/android/gpstest/library/util/CarrierFreqUtils.java
Add the ability to properly detect BDS B2b and IRNSS L1.
1. BDS "B2" is rename to "B2b", as B2I signal is marked as obsolete in official press release and due to the fact that they share the same frequency. I highly doubt any civilian device is going to support B2I. More detail see #652
> Source: http://www.beidou.gov.cn/yw/xwzx/201712/t20171226_11012.html
2. IRNSS L1 support, see #653. 
3. Remove the code for "B1-2" signal. I think it's an out-of-date mistake. I have checked every website, paper, press there is no such signal.
4. Rename B1 and B3 to B1I and B3I to match the official name. (It's uppercase "i", not lowercase “L”)
Maybe this will reduce user's confusion. as there are two B1 band.
And yes B3I is not obsolete. It may be supported by consumer market one day.
And the precise …
> Add support for BDS B2b and IRNSS L1. And update signal detection to match the actual BDS

- .github/workflows/android.yml
This PR fix bug ticket #729 by ensuring that the crashpad_handler process doesn't hang indefinitely after emulator exit
> CI: terminate crashpad_handler process on emulator exit (Fix #729)

- GPSTest/src/main/java/com/android/gpstest/ui/sky/SkyFragment.kt
Adds the diamond and dashes to the list of shapes and lines so that the colors get updated appropriately when dark mode is turned on
> Sets the correct color for the SouthPAN Legend diamond and dashes
