- GPSTest/src/main/AndroidManifest.xml
- GPSTest/src/main/java/com/android/gpstest/GpsTestActivity.java
- GPSTest/src/main/java/com/android/gpstest/HelpActivity.java
- GPSTest/src/main/res/layout/activity_help.xml
- GPSTest/src/main/res/menu/gps_menu.xml
- GPSTest/src/main/res/values-w820dp/dimens.xml
- GPSTest/src/main/res/values/dimens.xml
- GPSTest/src/main/res/values/strings.xml
> Fix #19 - Add Help Activity

- GPSTest/src/main/java/com/android/gpstest/GpsSkyFragment.java
- GPSTest/src/main/res/drawable/circle.xml
- GPSTest/src/main/res/drawable/pentagon.xml
- GPSTest/src/main/res/drawable/square.xml
- GPSTest/src/main/res/drawable/triangle.xml
- GPSTest/src/main/res/layout/gps_sky.xml
- GPSTest/src/main/res/layout/gps_sky_shape_legend.xml
- GPSTest/src/main/res/layout/gps_sky_signal_legend.xml
- GPSTest/src/main/res/values/dimens.xml
- GPSTest/src/main/res/values/strings.xml
> Fix #139 - Add shape-to-flag/name legend to Sky view

- GPSTest/src/main/java/com/android/gpstest/util/GpsTestUtil.java
- GPSTest/src/test/java/com/android/gpstest/GpsTestUtilTest.java
See http://gpsworld.com/innovation-qzs-3-and-qzs-4-join-the-quasi-zenith-satellite-system/
Especially Tables 2 and 3, Figure 4.
> Change QZSS "LEX" to "L6"

- GPSTest/src/main/java/com/android/gpstest/GpsTestActivity.java
- GPSTest/src/main/java/com/android/gpstest/HelpActivity.java
- GPSTest/src/main/java/com/android/gpstest/NavigationDrawerFragment.java
- GPSTest/src/main/java/com/android/gpstest/util/GpsTestUtil.java
- GPSTest/src/main/java/com/android/gpstest/util/LocationUtils.java
- GPSTest/src/main/java/com/android/gpstest/util/UIUtils.java
- GPSTest/src/main/res/values/do_not_translate.xml
- GPSTest/src/main/res/values/strings.xml
* This adds feedback menu item to nav drawer
TODO:
> Fix #166 -  Add feedback option to navigation drawer

- GPSTest/src/main/res/values-de-rDE/strings.xml
string "main_help_whatsnew" updated
> Fix #177 - Update German translation

- FAQ.md
> fix article url in FAQ.md

- FAQ.md
> Moto G: 2013, not 2018

- GPSTest/src/main/res/values-nl/strings.xml
> Update dutch translation

- GPSTest/src/main/res/values-nl/arrays.xml
- GPSTest/src/main/res/values-nl/strings.xml
Please check if all is transation. Did a manual compare with the english file.
- [ x] Acknowledge that you're contributing your code under Apache v2.0 license
- [ x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.
> Fix #222 - Update Dutch translation

- GPSTest/src/main/res/values-de-rDE/arrays.xml
- GPSTest/src/main/res/values-de-rDE/strings.xml
> German translation update

- GPSTest/src/main/res/values-zh-rCN/arrays.xml
- GPSTest/src/main/res/values-zh-rCN/strings.xml
- [ x ] Acknowledge that you're contributing your code under Apache v2.0 license
- [ - ] Apply the `AndroidStyle.xml` style template to your code in Android Studio.
I think that the former Chinese translation is no so good. E.g. he translated "longitude" as "length" just because "longitude" is written as "Long"? Maybe machine translation?
If you updated something else, you could contact me do complete its translation.
> rewrite: Chinese translation

- GPSTest/src/main/res/values-zh-rCN/strings.xml
I took a look into the effect made by shorten MSL. It worked well, but some other words needed to be shortened. H/Vs are those strings.
I'm sure that normally all the info can be fully displayed.
> fix Chinese: Sync and shorten H/V

- GPSTest/src/main/res/values-ja/strings.xml
> fix: Japanese translation(@extrajoker)

- .travis.yml
- GPSTest/src/androidTest/java/com/android/gpstest/LocationUtilsTest.java
Based on https://github.com/JakeWharton/butterknife/blob/master/.travis.yml
> Fix #259 - Fix emulator-based testing on Travis

- FAQ.md
> Update FAQ.md to include Xiaomi Mi 9

- FAQ.md
> Update Galileo constellation information link

- GPSTest/src/main/java/com/android/gpstest/GpsTestActivity.java
- GPSTest/src/main/java/com/android/gpstest/io/FileLogger.java
> Fix #404 - Re-use log file on orientation change

- GPSTest/src/google/java/com/android/gpstest/GpsMapFragment.java
- GPSTest/src/main/java/com/android/gpstest/BenchmarkViewModel.java
- GPSTest/src/main/java/com/android/gpstest/GpsTestActivity.java
- GPSTest/src/main/java/com/android/gpstest/NavigationDrawerFragment.java
An app should use interfaces (i.e. List) and instantiate using an implementation (i.e. ArrayList).
Hope this change helps a little bit for code clarity.
> chore: Cleanup of List

- GPSTest/src/androidTest/java/com/android/gpstest/IOUtilsTest.kt
- GPSTest/src/main/java/com/android/gpstest/GpsTestActivity.java
- GPSTest/src/main/java/com/android/gpstest/Preferences.java
- GPSTest/src/main/java/com/android/gpstest/io/CsvFileLogger.java
- GPSTest/src/main/java/com/android/gpstest/util/IOUtils.java
- GPSTest/src/main/res/values-cs-rCZ/strings.xml
- GPSTest/src/main/res/values-fi/strings.xml
- GPSTest/src/main/res/values-in/strings.xml
- GPSTest/src/main/res/values-it/strings.xml
- GPSTest/src/main/res/values-pl/strings.xml
- GPSTest/src/main/res/values-ru/strings.xml
- GPSTest/src/main/res/values-zh-rCN/strings.xml
- GPSTest/src/main/res/values/do_not_translate.xml
- GPSTest/src/main/res/values/strings.xml
- GPSTest/src/main/res/xml/preferences.xml
Follows same format as GnssLogger
Closes #472
> feat: Add support for logging GnssAntennaInfo to CSV 

- README.md
Improved readme, reorganized items, added screenshots and badges. you can see the readme at my fork here: https://github.com/aha999/gpstest/blob/master/README.md
> docs: Improved Readme - reorg, add screenshots

- README.md
> Replace dead link in README.md

- GPSTest/build.gradle
- GPSTest/src/main/AndroidManifest.xml
- GPSTest/src/main/java/com/android/gpstest/ui/MainActivity.kt
- GPSTest/src/main/java/com/android/gpstest/ui/Preferences.kt
- GPSTest/src/main/java/com/android/gpstest/util/UIUtils.kt
- GPSTest/src/main/res/layout/notification_permissions_dialog.xml
- GPSTest/src/main/res/xml/preferences.xml
- library/src/main/java/com/android/gpstest/library/data/SharedSensorManager.kt
- library/src/main/java/com/android/gpstest/library/util/LibUIUtils.kt
- library/src/main/java/com/android/gpstest/library/util/PermissionUtils.java
- library/src/main/res/values/do_not_translate.xml
- library/src/main/res/values/strings.xml
Also make several changes needed to bump targetSdkVersion to 33.
Fixes https://github.com/barbeau/gpstest/issues/694 and fixes https://github.com/barbeau/gpstest/issues/622
> feat: Implementation runtime permissions for notification

- .github/workflows/android.yml
- gradle/wrapper/gradle-wrapper.properties
This PR update the version of the Gradle Wrapper to the latest revision, and adapts the workflow to force use the same version. This will also removes the necessity to manually update the workflow in case of future updates.
> Upgrade Gradle Wrapper to v8.14.3
